#!/bin/bash -e

if git status --porcelain 2>/dev/null | grep -q .
then
  echo "Working copy is dirty" >&2
  exit 1
fi

source make_site

git checkout gh-pages
cp -rf site/* .
rm -rf site

git add .
git commit -m "updated site"
git push origin gh-pages
git checkout master
